# Generated by Django 4.2.14 on 2024-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='resimler/', verbose_name='Film Resmi'),
        ),
        migrations.AddField(
            model_name='film',
            name='yuklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
